# Generated by Django 4.1.7 on 2023-06-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
    ]
