# Generated by Django 4.1.7 on 2023-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_remove_userprofile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
