# Generated by Django 4.1.7 on 2023-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_userprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institute',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
